version: '3'
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app
    networks:
      - app
    depends_on:
      - redis
  redis:
    image: redis
    ports:
      - "6379"
    networks:
      - app
networks:
  app:
